//-------------CLASS----------
export const SAVE_GET_LIST_CLASS = "SAVE_GET_LIST_CLASS";
export const SET_MODAL_CLASS_OPEN = "SET_MODAL_CLASS_OPEN";
export const SET_SELECTED_CLASS = "SET_SELECTED_CLASS";
export const SET_VIEW_CLASS_MODAL = "SET_VIEW_CLASS_MODAL";
export const SET_VIEW_STUDENT_IN_CLASS = "SET_VIEW_STUDENT_IN_CLASS";
export const SAVE_UPDATE_CLASS = "SAVE_UPDATE_CLASS";
export const SAVE_CREATE_CLASS = "SAVE_CREATE_CLASS";
export const GET_LIST_ID_CLASS = "GET_LIST_ID_CLASS";
export const SAVE_CREATE_SUBJECT = "SAVE_CREATE_SUBJECT";

//--------------STUDENT---------
export const SAVE_GET_LIST_STUDENT = "SAVE_GET_LIST_STUDENT";
export const SET_SELECTED_STUDENT = "SET_SELECTED_STUDENT";
export const SET_MODAL_STUDENT_OPEN = "SET_MODAL_STUDENT_OPEN";
export const SAVE_CREATE_STUDENT = "SAVE_CREATE_STUDENT";
export const SAVE_UPDATE_STUDENT = "SAVE_UPDATE_STUDENT";
export const SAVE_RECEIVE_MAIL = "SAVE_RECEIVE_MAIL";
export const SAVE_SUBJECT_MAIL = "SAVE_SUBJECT_MAIL";

//--------------SUBJECT---------
export const SAVE_GET_LIST_SUBJECT = "SAVE_GET_LIST_SUBJECT";
export const SAVE_SELECTED_SUBJECT = "SAVE_SELECTED_SUBJECT";
export const SET_ADD_SUBJECT_MODAL = "SET_ADD_SUBJECT_MODAL";
export const SAVE_UPDATE_SUBJECT = "SAVE_UPDATE_SUBJECT";
export const SET_EDIT_SUBJECT_MODAL = "SET_EDIT_SUBJECT_MODAL";
export const GET_LIST_ID_SUBJECT = "GET_LIST_ID_SUBJECT";

//--------------USER---------
export const SAVE_INFOMATION_SIGN_IN = "SAVE_INFOMATION_SIGN_IN";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const USER_LOG_OUT = "USER_LOG_OUT";
